"""Native versus manufactured identity; no historical ranking claims."""

from dataclasses import replace

import pytest

from vaxrank.construct_sequence import (
    ConstructChemicalModification,
    ConstructEvidence,
    ConstructSequence,
    ConstructSequenceEdit,
)
from vaxrank.native_serialization import from_native_json, to_native_json
from vaxrank.vaccine_antigen import (
    AminoAcidInterval,
    TargetableMask,
    TumorSpecificityAttestation,
    VaccineAntigen,
)


SOURCE = "https://osteosarc.com/variant/DYNC1H1-chr14-101980529/"
# Independent published expectations, not generated by the mapping implementation.
NATIVE = "GKRFHATISFDTDTGLKQALET"
JLF = "GKRFHATISFDTDTGLKQALETKK"
DOCUMENTED = ConstructEvidence(
    source=SOURCE, evidence_level="documented", provider="JLF",
    vaccine_version="V2/V3", description="Published DYNC1H1 vaccine peptide")
RATIONALE = ConstructEvidence(
    source="User report, 2026-09-09", evidence_level="reported", provider="JLF",
    description="JLF uses terminal lysines as solubility extras; CSBio involvement uncertain")


def native_antigen(sequence=NATIVE, intervals=((7, 8),), kind="mutation"):
    return VaccineAntigen(
        kind=kind, amino_acids=sequence,
        targetable_mask=TargetableMask(tuple(AminoAcidInterval(*x) for x in intervals)),
        tumor_specificity=TumorSpecificityAttestation(
            status="admitted", evidence_kind="test_evidence",
            evidence_source="fixture", patient_specific=True),
        gene_name="DYNC1H1", gene_id="ENSG00000197102",
        transcript_ids=("NM_001376",), protein_ids=("Q14204",),
        species="human", source_identifier="chr14:101980529:G>A")


def construct(sequence=NATIVE, *, native=None, edits=(), **kwargs):
    native = native or native_antigen()
    return ConstructSequence(
        name="DYNC1H1", sequence=sequence, modality="peptide", evidence=DOCUMENTED,
        native_antigen=native, native_start=0, native_end=len(native.amino_acids),
        sequence_edits=edits, **kwargs)


def test_documented_jlf_tail_retains_native_identity_without_rna_coordinates():
    edit = ConstructSequenceEdit(22, 22, "KK", DOCUMENTED, RATIONALE)
    result = construct(JLF, edits=(edit,))
    assert len(result.sequence) == 24
    assert result.native_sequence == NATIVE
    assert result.native_residue_offsets == tuple(range(22)) + (None, None)
    assert result.targetable_mask == TargetableMask((AminoAcidInterval(7, 8),))
    assert result.modification_boundaries == (22,)
    assert result.removed_target_intervals == ()
    assert result.sequence_edits[0].rationale.evidence_level == "reported"
    assert result.native_antigen.amino_acids == NATIVE
    final = result.assessment_antigen()
    assert final.amino_acids == JLF
    assert final.source_identifier != result.native_antigen.source_identifier
    assert final.transcript_ids == ("NM_001376",)
    assert final.species == "human"


@pytest.mark.parametrize("kind", ["mutation", "CTA", "viral", "ERV", "splice"])
def test_nonmutation_masks_do_not_assign_targetability_to_added_residues(kind):
    native = native_antigen("ACDEFG", ((0, 6),), kind=kind)
    result = construct("KACDKEFGKK", native=native, edits=(
        ConstructSequenceEdit(0, 0, "K", DOCUMENTED),
        ConstructSequenceEdit(3, 3, "K", DOCUMENTED),
        ConstructSequenceEdit(6, 6, "KK", DOCUMENTED),
    ))
    assert result.native_residue_offsets == (None, 0, 1, 2, None, 3, 4, 5, None, None)
    assert result.targetable_mask.intervals == (
        AminoAcidInterval(1, 4), AminoAcidInterval(5, 8))
    assert result.assessment_antigen().kind == kind


@pytest.mark.parametrize("replacement, sequence", [("", "ACDFG"), ("KK", "ACDKKFG")])
def test_deleted_or_substituted_target_does_not_acquire_new_native_support(replacement, sequence):
    native = native_antigen("ACDEFG", ((3, 4),))
    result = construct(sequence, native=native, edits=(
        ConstructSequenceEdit(3, 4, replacement, DOCUMENTED),))
    assert result.targetable_mask.intervals == ()
    assert result.removed_target_intervals == (AminoAcidInterval(3, 4),)
    assert result.assessment_antigen().tumor_specificity.status == "held_out"
    assert native.tumor_specificity.status == "admitted"


def test_preserve_native_deletion_junction_only_when_its_neighbors_remain_adjacent():
    native = native_antigen("ACDEFG", ((3, 3),))
    intact = construct("KACDEFG", native=native, edits=(
        ConstructSequenceEdit(0, 0, "K", DOCUMENTED),))
    assert intact.targetable_mask.intervals == (AminoAcidInterval(4, 4),)
    assert not intact.removed_target_intervals
    interrupted = construct("ACDKEFG", native=native, edits=(
        ConstructSequenceEdit(3, 3, "K", DOCUMENTED),))
    assert interrupted.targetable_mask.intervals == ()
    assert interrupted.removed_target_intervals == (AminoAcidInterval(3, 3),)


def test_explicit_window_disambiguates_repeated_native_sequence():
    native = native_antigen("ACDACD", ((4, 5),))
    result = ConstructSequence(
        name="repeat", sequence="ACDK", modality="peptide", evidence=DOCUMENTED,
        native_antigen=native, native_start=3, native_end=6,
        sequence_edits=(ConstructSequenceEdit(6, 6, "K", DOCUMENTED),))
    assert result.native_residue_offsets == (3, 4, 5, None)
    assert result.targetable_mask.intervals == (AminoAcidInterval(1, 2),)
    assert result.modification_boundaries == (3,)


def test_unresolved_mapping_never_selects_first_occurrence():
    result = ConstructSequence(
        name="unknown", sequence=JLF, modality="peptide", evidence=DOCUMENTED,
        native_antigen=native_antigen(), mapping_status="unresolved",
        mapping_reason="Native boundaries have not been independently established")
    assert result.native_residue_offsets == (None,) * 24
    assert result.native_sequence is None
    assert result.sequence_prediction_unassessed_reason == "unresolved_native_mapping"
    assert result.removed_target_intervals is None
    with pytest.raises(ValueError, match="unassessed"):
        result.assessment_antigen()
    assert from_native_json(to_native_json(result), ConstructSequence) == result


def test_chemical_form_changes_identity_not_sequence_and_is_not_silently_predicted():
    native = construct()
    chemical = ConstructChemicalModification(22, 22, "C-terminal amidation", DOCUMENTED)
    modified = replace(native, chemical_modifications=(chemical,))
    assert modified.sequence == native.sequence
    assert modified.cache_identity != native.cache_identity
    assert modified.native_residue_offsets == native.native_residue_offsets
    assert modified.sequence_prediction_unassessed_reason == "unsupported_chemical_modifications"
    with pytest.raises(ValueError, match="unassessed"):
        modified.assessment_antigen()
    for modality in ("mrna", "dna"):
        with pytest.raises(ValueError, match="not encoded"):
            replace(modified, modality=modality)
        encoded = replace(native, modality=modality)
        assert encoded.assessment_antigen().amino_acids == NATIVE


def test_complete_native_graph_roundtrip_and_content_identity():
    result = construct(JLF, edits=(ConstructSequenceEdit(22, 22, "KK", DOCUMENTED, RATIONALE),),
                       chemical_modifications=(
                           ConstructChemicalModification(0, 0, "N-acetylation", DOCUMENTED),))
    restored = from_native_json(to_native_json(result), ConstructSequence)
    assert restored == result
    assert restored.cache_identity == result.cache_identity
    changed_source = replace(result.native_antigen, source_identifier="another occurrence")
    assert replace(result, native_antigen=changed_source).cache_identity != result.cache_identity
    changed_evidence = replace(DOCUMENTED, vaccine_version="another version")
    assert replace(result, evidence=changed_evidence).cache_identity != result.cache_identity


@pytest.mark.parametrize("start,end,replacement", [
    (-1, 0, "K"), (3, 2, "K"), (True, 3, "K"), (1.0, 3, "K"),
    (0, 0, ""), (0, 1, "X"),
])
def test_invalid_edits_rejected(start, end, replacement):
    with pytest.raises(ValueError):
        ConstructSequenceEdit(start, end, replacement, DOCUMENTED)


@pytest.mark.parametrize("edits", [
    (ConstructSequenceEdit(23, 23, "K", DOCUMENTED),),
    (ConstructSequenceEdit(0, 1, "G", DOCUMENTED),),
    (ConstructSequenceEdit(3, 7, "K", DOCUMENTED), ConstructSequenceEdit(5, 6, "K", DOCUMENTED)),
    (ConstructSequenceEdit(0, 0, "K", DOCUMENTED), ConstructSequenceEdit(0, 0, "K", DOCUMENTED)),
])
def test_out_of_range_noop_overlapping_or_ambiguous_edits_rejected(edits):
    with pytest.raises(ValueError):
        construct(edits=edits)


def test_final_sequence_must_be_exactly_explained():
    with pytest.raises(ValueError, match="do not reproduce"):
        construct(JLF)
    with pytest.raises(ValueError, match="requires a reason"):
        ConstructSequence("x", JLF, "peptide", DOCUMENTED, mapping_status="unresolved")
    with pytest.raises(ValueError, match="cannot assert"):
        replace(construct(), mapping_status="unresolved", mapping_reason="unknown")


@pytest.mark.parametrize("start,end", [(1, 1), (0, 23), (23, 23)])
def test_chemical_coordinates_are_final_and_termini_are_explicit(start, end):
    with pytest.raises(ValueError):
        construct(chemical_modifications=(
            ConstructChemicalModification(start, end, "change", DOCUMENTED),))


@pytest.mark.parametrize("changes", [
    {"evidence": "unattributed"}, {"native_antigen": "untyped"},
    {"sequence_edits": [{"start": 22, "end": 22, "replacement": "KK"}]},
    {"chemical_modifications": ["acetyl"]}, {"sequence": ["A", "C"]},
])
def test_untyped_native_input_cannot_bypass_provenance_validation(changes):
    with pytest.raises(ValueError):
        replace(construct(), **changes)
