# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from .core_logic import run_vaxrank
from .epitope_config import EpitopeConfig
from .epitope_logic import predict_epitopes
from .candidate_epitope import CandidateEpitope, Peptide
from .vaccine_config import VaccineConfig
from .vaccine_antigen import (
    AminoAcidInterval,
    SelfReferenceMatch,
    SelfReferenceSource,
    TargetableMask,
    TumorSpecificityAttestation,
    TumorSpecificityEvidence,
    VaccineAntigen,
)
from .vaccine_peptide import VaccinePeptide
from .vaccine_library import antigen_construct_name, select_antigen_window
from .safety_assessment import (
    AntigenSafetyAssessment,
    ConstructBoundary,
    EmittedSafetyLigand,
    SafetyAssessmentError,
    SafetyPrediction,
    SafetyPredictionCoverage,
    WindowSafetyAssessment,
    assess_antigen_safety,
    assess_vaccine_antigen_window,
    near_self_queries_for_window,
    safety_assessment_from_prediction_frame,
)
from .safety_policy import (
    DEFAULT_SAFETY_ENFORCEMENT_POLICY,
    SAFETY_MODE_AUDIT,
    SAFETY_MODE_ENFORCE,
    SAFETY_MODE_OFF,
    AntigenSafetyPolicyDecision,
    SafetyEnforcementPolicy,
    SafetyLigandDecision,
    SafetyPercentileThreshold,
    SafetyPolicyError,
    evaluate_antigen_safety_policy,
)
from .tissue_risk import (
    HPAEvidenceCoverage,
    HPAReferenceProvenance,
    SafetyTissueGroup,
    TissueRiskAssessment,
    TissueRiskDerivationError,
    TissueRiskEvidence,
    TissueRiskPolicy,
    TissueRiskProtein,
    build_hpa_reference_provenance,
    derive_tissue_risk_proteins,
    resolve_tissue_risk_policy,
)
from .risk_ligand import (
    PROTEIN_RESOLUTION_ALL_ISOFORMS,
    PROTEIN_RESOLUTION_LONGEST_ISOFORM,
    PatientHLARiskLigandIndex,
    ProteinResolutionCoverage,
    ResolvedRiskProtein,
    RiskCoverageGap,
    RiskLigand,
    RiskLigandCoverage,
    RiskLigandError,
    RiskLigandIndexProvenance,
    RiskLigandPrediction,
    RiskLigandSelectionPolicy,
    RiskLigandSource,
    RiskPercentileThreshold,
    RiskProteinSequenceSet,
    build_patient_hla_risk_ligand_index,
    resolve_tissue_risk_protein_sequences,
    risk_ligand_index_from_prediction_frame,
)
from .near_self import (
    BLOSUM62,
    DEFAULT_NEAR_SELF_COMPARATOR,
    AminoAcidSubstitutionMatrix,
    HammingRiskComparator,
    NearSelfAssessment,
    NearSelfError,
    NearSelfQuery,
    NearestRiskLigandHit,
    SimilarityComparatorProvenance,
    SubstitutionEvidence,
    assess_near_self,
    assess_near_self_queries,
)
from .cta_admission import (
    CTAAdmissionAssessment,
    CTAAdmissionError,
    CTAAdmissionPolicy,
    CTAOverrideEvidence,
    CTAReferenceEvidence,
    PatientTumorExpressionEvidence,
    assess_cta_antigen,
    build_cta_vaccine_antigen,
)
from .reference_proteome import self_reference_matches
from .version import __version__

__all__ = [
    "__version__",
    "AminoAcidInterval",
    "AminoAcidSubstitutionMatrix",
    "AntigenSafetyAssessment",
    "AntigenSafetyPolicyDecision",
    "BLOSUM62",
    "CandidateEpitope",
    "CTAAdmissionAssessment",
    "CTAAdmissionError",
    "CTAAdmissionPolicy",
    "CTAOverrideEvidence",
    "CTAReferenceEvidence",
    "ConstructBoundary",
    "DEFAULT_NEAR_SELF_COMPARATOR",
    "DEFAULT_SAFETY_ENFORCEMENT_POLICY",
    "EmittedSafetyLigand",
    "EpitopeConfig",
    "HPAEvidenceCoverage",
    "HPAReferenceProvenance",
    "HammingRiskComparator",
    "NearSelfAssessment",
    "NearSelfError",
    "NearSelfQuery",
    "NearestRiskLigandHit",
    "Peptide",
    "PROTEIN_RESOLUTION_ALL_ISOFORMS",
    "PROTEIN_RESOLUTION_LONGEST_ISOFORM",
    "PatientHLARiskLigandIndex",
    "PatientTumorExpressionEvidence",
    "ProteinResolutionCoverage",
    "ResolvedRiskProtein",
    "RiskCoverageGap",
    "RiskLigand",
    "RiskLigandCoverage",
    "RiskLigandError",
    "RiskLigandIndexProvenance",
    "RiskLigandPrediction",
    "RiskLigandSelectionPolicy",
    "RiskLigandSource",
    "RiskPercentileThreshold",
    "RiskProteinSequenceSet",
    "SAFETY_MODE_AUDIT",
    "SAFETY_MODE_ENFORCE",
    "SAFETY_MODE_OFF",
    "SafetyAssessmentError",
    "SafetyPrediction",
    "SafetyPredictionCoverage",
    "SafetyEnforcementPolicy",
    "SafetyLigandDecision",
    "SafetyPercentileThreshold",
    "SafetyPolicyError",
    "SafetyTissueGroup",
    "SelfReferenceMatch",
    "SelfReferenceSource",
    "SimilarityComparatorProvenance",
    "SubstitutionEvidence",
    "TargetableMask",
    "TissueRiskAssessment",
    "TissueRiskDerivationError",
    "TissueRiskEvidence",
    "TissueRiskPolicy",
    "TissueRiskProtein",
    "TumorSpecificityAttestation",
    "TumorSpecificityEvidence",
    "VaccineAntigen",
    "VaccineConfig",
    "VaccinePeptide",
    "WindowSafetyAssessment",
    "assess_antigen_safety",
    "assess_vaccine_antigen_window",
    "assess_near_self",
    "assess_near_self_queries",
    "assess_cta_antigen",
    "antigen_construct_name",
    "build_hpa_reference_provenance",
    "build_patient_hla_risk_ligand_index",
    "build_cta_vaccine_antigen",
    "derive_tissue_risk_proteins",
    "evaluate_antigen_safety_policy",
    "near_self_queries_for_window",
    "predict_epitopes",
    "run_vaxrank",
    "resolve_tissue_risk_policy",
    "resolve_tissue_risk_protein_sequences",
    "risk_ligand_index_from_prediction_frame",
    "safety_assessment_from_prediction_frame",
    "self_reference_matches",
    "select_antigen_window",
]
