DEFAULT_SCHEMA_VERSION = 2

DEFAULT_LOGISTIC_EPITOPE_SCORE_MIDPOINT = 350.0
DEFAULT_LOGISTIC_EPITOPE_SCORE_WIDTH = 150.0
DEFAULT_MIN_EPITOPE_SCORE = 0.00001
DEFAULT_BINDING_AFFINITY_CUTOFF = 5000.0
DEFAULT_PERCENTILE_RANK_CUTOFF = 10.0

DEFAULT_VACCINE_PEPTIDE_LENGTH = 25
DEFAULT_PADDING_AROUND_MUTATION = 5
DEFAULT_MAX_VACCINE_PEPTIDES_PER_VARIANT = 1
DEFAULT_NUM_MUTANT_EPITOPES_TO_KEEP = 1000
DEFAULT_VACCINE_PEPTIDE_SCORE_FRACTION_OF_BEST = 0.99

DEFAULT_MANUFACTURABILITY_MAX_C_TERMINAL_HYDROPATHY = 1.5
DEFAULT_MANUFACTURABILITY_MIN_KMER_HYDROPATHY = 0.0
DEFAULT_MANUFACTURABILITY_MAX_KMER_HYDROPATHY_LOW_PRIORITY = 1.5
DEFAULT_MANUFACTURABILITY_MAX_KMER_HYDROPATHY_HIGH_PRIORITY = 2.5
