# -*- coding: utf-8 -*-
#
# vaxrank documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.

import os
import sys

# Add the parent directory to the path so we can import vaxrank
sys.path.insert(0, os.path.abspath('..'))

# -- General configuration ------------------------------------------------

# Sphinx extensions
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',  # Support for NumPy/Google style docstrings
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'vaxrank'
copyright = '2017-2025, Alex Rubinsteyn, Julia Kodysh'
author = 'Alex Rubinsteyn, Julia Kodysh'

# The version info for the project
# Import version from vaxrank
try:
    from vaxrank.version import __version__
    version = __version__
    release = __version__
except ImportError:
    version = 'dev'
    release = 'dev'

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for autodoc --------------------------------------------------

# Order members by source order instead of alphabetical
autodoc_member_order = 'bysource'

# Show type hints in documentation
autodoc_typehints = 'description'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# Theme options
html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# -- Options for HTMLHelp output ------------------------------------------

htmlhelp_basename = 'vaxrankdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}

latex_documents = [
    (master_doc, 'vaxrank.tex', 'vaxrank Documentation',
     'Alex Rubinsteyn, Julia Kodysh', 'manual'),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, 'vaxrank', 'vaxrank Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (master_doc, 'vaxrank', 'vaxrank Documentation',
     author, 'vaxrank',
     'Selection of mutated protein fragments for therapeutic personalized cancer vaccines.',
     'Miscellaneous'),
]
