# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout private netmhc-bundle repo
        uses: actions/checkout@v4
        with:
          repository: openvax/netmhc-bundle
          token: ${{ secrets.NETMHC_BUNDLE_ACCESS_TOKEN }}
          path: netmhc-bundle

      - name: Install netmhc-bundle dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: tcsh gawk python2-minimal
          version: 1.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest pytest-cov pylint 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install wkthtmltopdf
        run: |
          sudo apt-get install -y xfonts-base xfonts-75dpi
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with PyLint
        run: |
          ./lint.sh
      - name: Download Ensembl data
        run: |
          echo "Before installing Ensembl releases" && df -h
          pyensembl install --release 75 --species human --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCh37.75/
          pyensembl install --release 102 --species mouse --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCm38.102/
          echo "After installing Ensembl releases" && df -h
      - name: Test with pytest
        run: |
          # configure netmhc-bundle paths
          export NETMHC_BUNDLE_HOME=$PWD/netmhc-bundle
          echo "NetMHC-bundle dir:" && ls -l $NETMHC_BUNDLE_HOME
          mkdir $PWD/netmhc-bundle-tmp
          export NETMHC_BUNDLE_TMPDIR=$PWD/netmhc-bundle-tmp
          export PATH=$PATH:$NETMHC_BUNDLE_HOME/bin
          ./test.sh
